language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install --upgrade setuptools py pip
  - pip install .[all]

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist
  user: __token__
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
  password:
    secure: CeFMx8LxnY9RPIq9hB5VtpfF0OX99ZvhqwI9pUHfJGJfccugR09E40tjAbmkGFV+Q7H+bC46U3aJRzvl+66mKr7yBt8H5npIqLkzCvMYXsL9yWpzVggz6/tbmchzJFQbe0OcJnZvThTuyJjyhLUnhCSPh3w9EJsdblSEnjDXlAsPObBvOgGlkg0QSd/a0j4A9iR+jK4fLB7+JnR2cjejEX6NKULdqhRR4wl+YcnZQo96UstAQ2bHPPYE1gqsQZlYAk6IhV54DrIGGr0xGe8Rt746z/gkBPZyHx40gAimhoWe43xjZj9RNZmcfCalcflh1Pc/r/Yc0qJG9v7zG+KJG2b8w+EBjnZZvs0mg1W4CEE27Vi75eq0UqmcO81ej0+6YUFSjjCGJK9Dyyro6ZM5w2BjxqqNTHyItk516iUEN3HJ9G9ltrLiNw2gaV2fm51pIXE9j0pf9JgC2o0Min495I9AUOFEFUdiS7DPVc+sx21ELJntF5KLDvBOrPWurpk4MfhuzTfIWBn923dr33J/Gq+8uyQP01tm04N6MgNz4OhXT/xiuvTE86zkDmlhPNvEgkj4fjijHKHdpSk8GfdAKYcKSJarYabDbi3P0iTxd7YfcC5OUJoNdOAGh1aWGbazOaK0ZaNvLgAtyl4uEtHp/HLKmlo3L4zGu/Vc1qawLUE=
