language: python

python:
  - '3.4'
  - '3.5'

install:
  - pip install --upgrade setuptools py pip urllib3==1.18
  - pip install -r dev_requirements.txt
  - pip install .

script:
  - python setup.py test

deploy:
  - provider: pypi
    distributions: sdist
    server: "https://pypi.python.org/pypi"
    user: fact-deploybot
    password:
      secure: "KPjogBL/F/h/pAASSd8XTkl/fZQFV467GlIPRHhUMoJROFzNE4TxbC36DYXQZ5GMXjn6iD0sgklUqGdqTTAFdvAJ8Pp9UxKTIxx8DDSVYT0SBzmSaWMUxAI0eGxaZ2ln5I9BVbXXGemrgVXXoTGhQ5ErqucmUJURxkxcS91JQSaqcLMJAhHbAmV4+CW99mL821SpzEE0B8dC7zP2JrFfhJdgbt/Ny1KVWDaev6fVXwP7IPs83h8j/sTqR5nCaZtCAkDBN6ayY4CTQe7uMyZZkauqkhLwMuJgfFGlG1ZuSvAyYlANmhIy/MPAsWuNbXrv/iF7XKNSRAwfb0FajOK6s9muj+a6tI5M2kvhVLKZ8JK6n8CJbsSBmZCN+iLSKE5I33vjA1Nl97p0S+F0+1poJKy9gJuulGJLtVr9zJZq6jv/m6dUEMkNYHzZMul19n3Q30jdtTnuv3qjYwUaYRbYNP91KXVZlJYYPOAjKDF5No2AoKwRUzmoM6zhCJcQKf+5bCPe6jcNpie/KdMtogKK9qYVTxGBecg2HFwBo7ekWOVRzHzlkgYJohNAy22A8EDkqsSgY6HF3/AW5MmQQdua55G8wedRqg5YCQq+2PU7NECd9fqHs6n0NblLxdubsD8S49oiO6V8+nLuadH8DTZgXU2CHUHtzA1z5FqYt6gqyyo="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
